name: Aktualizacja XML Allegro

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz repozytorium
        uses: actions/checkout@v4

      - name: Przygotuj Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Uruchom generator XML
        run: python main.py

      - name: Zapisz zmiany
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add allegro_final.xml
          git commit -m "Automatyczna aktualizacja XML" || echo "Brak zmian"
          git push
